version: 2.1

requires-installed-packages: &requires-installed-packages
    requires:
        - test-our-code

#create environement
requires-node: &requires-node
    docker:
        - image: circleci/node

jobs:
    test-our-code:
        <<: *requires-node

        steps:
            - checkout
            - run:
                  name: install all packages
                  command: yarn install
            - run:
                  name: install linter
                  command: yarn add -D eslint @babel/eslint-parser
            - run:
                  name: test linting
                  command: |
                      pwd
                      yarn lint --ext .js,.vue --ignore-pattern .gitignore --ignore-pattern '*.test.js' --ignore-pattern '*.spec.js' --ignore-pattern 'nuxt.config.*' --ignore-pattern 'static/*' --ignore-pattern 'asset/*' .
#                      yarn lint -c ./.eslintrc --ext .vue,.js --fix --ignore-pattern ./gitignore  --ignore-pattern '*.spec.js' --ignore-pattern '*.test.js' .
#                yarn test
                # yarn lint --ext .vue,.js --debug --ignore-path ./.gitignore
# si activer la commande suivant ne s'execute que si l'étape plus haut n'est pas sucess
    run :
         name : run tests
         command : yarn test

#workflow declaration
workflows:
    version: 2
    main:
        jobs:
            - test-our-code:
                  filters:
                      branches:
                          only: /develop/
#      - run-linter:
#          <<: *requires-installed-packages

